import "~/styles/globals.css";
import { Playfair_Display, Lato } from "next/font/google";
import { twMerge } from "tailwind-merge";

const playfair = Playfair_Display({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-serif",
});

const lato = Lato({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          "mx-auto min-h-screen max-w-5xl border-x-2 border-solid border-stone-200 px-8",
          lato.variable,
          playfair.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
